# Generated by Django 3.2 on 2021-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancy', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('wage', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('name_job', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
